// Arquivo JS aula 07 DOM

// DOM = Document Object Model
// Arvore com elemento desde o Browser, a Janela do Browser, o Documento e cada elemento html que forma os conteudos.

// navigator
// window
// location
// document -> html -> head e body history

// PARA MANIPULAR O DOM PRECISAMOS
// indicar qual objeto usar, depois chamar 
// um método(função) para selecionar ele, seus dados, trazer 
// informações, etc.